name: rapid
description: The mobile app for rapid
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  feather_icons_flutter: ">=4.7.4"

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.2.1

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Thin.otf
          weight: 100
        - asset: fonts/Inter-ExtraLight.otf
          weight: 200
        - asset: fonts/Inter-Light.otf
          weight: 300
        - asset: fonts/Inter-Regular.otf
          weight: 400
        - asset: fonts/Inter-Medium.otf
          weight: 500
        - asset: fonts/Inter-SemiBold.otf
          weight: 600
        - asset: fonts/Inter-Bold.otf
          weight: 700
        - asset: fonts/Inter-ExtraBold.otf
          weight: 800
        - asset: fonts/Inter-Black.otf
          weight: 900

import_sorter:
  comments: false
